pipeline {
    agent {
        docker {
            dockerfile true
        }
    }

    environment {
        dockerImageName = 'alvonellos/choppala-www'
        // Define your Docker image name
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }

            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Build image') {
            steps {
                script {
                    def dockerImage = docker.build("${dockerImageName}:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Deploying container to Kubernetes') {
            steps {
                script {
                    kubernetesDeploy(configs: "kubernetes/deployment.yaml", "kubernetes/service.yaml")
                }
            }
        }
    }
}
