pipeline {
    agent any
    environment {
        dockerImageName = 'alvonellos/choppala-www'
        // Define your Docker image name
        kubernetesNamespace = 'choppala-www' // Update with your Kubernetes namespace
        kubeconfig = credentials('cluster') // Use the ID of the Kubernetes credential
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'mvn -B -DskipTests clean install -U'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'mvn test'
            }
        }

        stage('Build image') {
            steps {
                echo 'Building Docker image...'
                script {
                    def dockerImage = docker.build("${dockerImageName}:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                script {
                    docker.withRegistry('https://registry-1.docker.io', '65fbcb2c-d252-4e31-bacc-8e63f06f3d87') {
                        // Use the ID of the Jenkins credentials that store Docker Hub username and password
                        def dockerImage = docker.image("${dockerImageName}:${env.BUILD_NUMBER}")
                        dockerImage.push()
                    }
                }
            }
        }

        stage('List pods') {
          withKubeConfig([credentialsId: 'kubernetes-config']) {
              sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'
              sh 'chmod u+x ./kubectl'
              sh './kubectl get pods'
          }
        }


        stage('Check Kubernetes') {
            steps {
                echo 'Getting kubectl'
                script {
                    sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'
                    sh 'chmod u+x ./kubectl'
                    sh './kubectl get pods'
                    sh "${kubectl} version"
                    sh "${kubectl} config view"
                }
            }
        }

        stage('Delete Old Namespace') {
            steps {
                script {
                    sh "kubectl delete namespace ${KUBE_NAMESPACE} --ignore-not-found=true"
                }
            }
        }

       stage('Create New Namespace') {
            steps {
                script {
                    sh "kubectl create namespace ${KUBE_NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Use the Kubernetes plugin to deploy to the cluster
                    def kubeconfig = credentials('cluster') // Use the ID of the Kubernetes credential
                    sh "kubectl --kubeconfig=${kubeconfig} apply -f kubernetes/deployment.yaml -n ${kubernetesNamespace}"
                    sh "kubectl --kubeconfig=${kubeconfig} apply -f kubernetes/service.yaml -n ${kubernetesNamespace}"
                }
            }
        }
    }
}
