apiVersion: apps/v1
kind: Deployment
metadata:
  name: choppala-www #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: choppala-www
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: choppala-www
  template:
    metadata:
      labels:
        app: choppala-www
    spec:
      containers:
        - name: choppala-www #The name of the container
          image: alvonellos/choppala-www:$BUILD_NUMBER #The Docker image for building the React.js application container
          imagePullPolicy: Always
          ports:
            - containerPort: 5000  #The port for the spring application   container