apiVersion: apps/v1
kind: Deployment
metadata:
  name: choppala-www-ng
  labels:
    app: choppala-www-ng
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: choppala-www-ng
  template:
    metadata:
      labels:
        app: choppala-www-ng
    spec:
      containers:
        - name: choppala-www-ng #The name of the container
          image: alvonellos/choppala-www-ng:$BUILD_NUMBER #The Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              hostPort: 8088
              hostIP: 0.0.0.0
              protocol: "TCP"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: TOKEN

