apiVersion: v1
kind: Service
metadata:
  name: choppala-www #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: choppala-www
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.71
  loadBalancerIP: 192.168.0.71
  ports:
    - port: 80 #Service port
      targetPort: 8080
      protocol: TCP #The port for the container