apiVersion: v1
kind: Service
metadata:
  name: choppala-www #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: choppala-www
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.70
  ports:
    - protocol: TCP
      port: 80 #Service port
      targetPort: 80 #The port for the container