apiVersion: v1
kind: Service
metadata:
  name: choppala-www #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: choppala-www
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 172.16.253.2
  loadBalancerIP: 172.16.253.2
  ports:
    - port: 80 #Service port
      targetPort: 8002
      protocol: TCP #The port for the container