apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choppala-www-ingress
spec:
  rules:
    - host: choppala-www.home.alvonellos.com  # Replace with your actual domain or IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: choppala-www
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: choppala-www
spec:
  selector:
    app: choppala-www
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
