apiVersion: v1
kind: Service
metadata:
  name: choppala-www-ng #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: choppala-www-ng
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.78
  loadBalancerIP: 192.168.0.78
  ports:
    - port: 80 #Service port
      targetPort: 8088
      protocol: TCP #The port for the container